ci: fix error ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -31,8 +31,13 @@ jobs:
 
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip setuptools wheel
-          pip install -r requirements.txt
+          if [ -f requirements.txt ]; then
+            python -m pip install --upgrade pip setuptools wheel
+            pip install -r requirements.txt
+          else
+            echo "Error: requirements.txt not found in the 'src/' directory."
+            exit 1
+          fi
 
       - name: Run main.py
         run: python main.py
